void _puts_recursion(char *s);
void _print_rev_recursion(char *s);
int _strlen_recursion(char *s);
int factorial(int n);
int _pow_recursion(int x, int y);
int _sqrt_recursion(int n);
int is_prime_number(int n);
int is_palindrome(char *s);
int _putchar(char c);
int natural_root(int divisor, int x);
int is_prime(int divisor, int x);
int palindrome(int beg, int end, char *str);
int wildcmp(char *s1, char *s2);
